SELECT J.FLAVOR
FROM (
SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER)AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR
) AS J
LEFT JOIN FIRST_HALF F
ON J.FLAVOR = F.FLAVOR
GROUP BY J.FLAVOR
ORDER BY (J.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3